// no-port-check: Independent numeric oracles and real native rendering fixtures.
#include <QtTest>
#include <QPainter>
#include <QDir>
#include <QScreen>
#include <QJsonArray>
#include "gui/meters/presets/CompositePresetItem.h"
#include "gui/meters/presets/BarPresetItem.h"
#include "gui/meters/presets/CrossNeedleItem.h"
#include "gui/meters/presets/AnanMultiMeterItem.h"
#include "gui/meters/presets/PowerSwrPresetItem.h"
#include "gui/meters/presets/MagicEyePresetItem.h"
#include "gui/meters/presets/SignalTextPresetItem.h"
#include "gui/meters/presets/ContestPresetItem.h"
#include "gui/meters/BandButtonItem.h"
#include "gui/meters/ModeButtonItem.h"
#include "gui/meters/VfoDisplayItem.h"
#include "gui/meters/ClockItem.h"
#include "gui/meters/MeterWidget.h"
#include "gui/meters/MeterPoller.h"
#include "gui/meters/ItemGroup.h"
#include "models/RadioModel.h"
#include "core/RadioStatus.h"
#include "core/mmio/MmioEndpoint.h"
#include "gui/containers/ContainerContentRegistry.h"
#include "gui/containers/ContainerButtonDispatcher.h"
#include "models/SliceModel.h"
#include "models/Band.h"
using namespace NereusSDR;
class TestCompositePresets:public QObject {
    Q_OBJECT
private:
    static QJsonArray configuredChannels(CompositePresetItem& face) {
        QJsonArray channels=face.configuration()["channels"].toArray();
        for(int i=0;i<channels.size();++i) { auto c=channels[i].toObject(); c["ignoreHistoryMs"]=0; channels[i]=c; } return channels;
    }
private slots:
    void paletteRoundtrips() {
        ContainerContentRegistry registry; int complete=0;
        for(const auto& descriptor:registry.descriptors()) {
            if(!descriptor.typeId.startsWith("meter.")) { continue; }
            ContentEntry entry=registry.makeEntry(descriptor.typeId);
            if(descriptor.typeId=="meter.adcMax") { QVERIFY(!descriptor.available); QVERIFY(!registry.createMeterItem(entry,nullptr)); QVERIFY(descriptor.unavailableReason.contains("magnitude")); continue; }
            std::unique_ptr<MeterItem> item(registry.createMeterItem(entry,nullptr)); QVERIFY2(item,qPrintable(descriptor.typeId));
            if(auto* face=qobject_cast<CompositePresetItem*>(item.get())) {
                auto edit=face->configuration(); if(face->editableFields().contains("title")) { edit["title"]="Edited | title"; } if(face->editableFields().contains("backdropColor")) { edit["backdropColor"]="#ff102030"; } edit["future"]=QJsonObject{{"keep",true}}; edit["faceHeight"]=320;
                QVERIFY(face->applyConfiguration(edit)); QCOMPARE(face->preferredFaceHeight(),320); QVERIFY(face->minimumFaceSize().width()>=260);
                const QString before=face->serialize(); QVERIFY(!face->applyConfiguration({{"w",-1}})); QCOMPARE(face->serialize(),before);
                if(!edit["channels"].toArray().isEmpty()) { auto channels=edit["channels"].toArray(); auto c=channels[0].toObject(); c["attack"]=2; channels[0]=c; QVERIFY(!face->applyConfiguration({{"channels",channels}})); QCOMPARE(face->serialize(),before); }
            } else if(auto* face=qobject_cast<BarPresetItem*>(item.get())) { QVERIFY(face->applyConfiguration({{"label","Edited | title"},{"titleColor","#ffff0000"},{"attack",.4},{"decay",.2},{"future",QJsonObject{{"keep",true}}}})); }
            ContentEntry saved=registry.captureMeterItem(*item,entry); QCOMPARE(saved.config["legacyRecord"],entry.config["legacyRecord"]);
            std::unique_ptr<MeterItem> copy(registry.createMeterItem(saved,nullptr)); QVERIFY(copy); QCOMPARE(copy->serialize(),item->serialize());
            std::unique_ptr<ItemGroup> group(ItemGroup::createCompletePreset(descriptor.typeId)); QCOMPARE(group->items().size(),1); ++complete;
        }
        QVERIFY(complete>=29);
    }
    void allBarCalibrationsAndAbsence() {
        struct Row { const char* flavor; int primary,secondary; double low,middle,high,x; const char* units; };
        // Numeric oracle transcribed from the saved source audit, never generated by product helpers.
        const QList<Row> rows{{"Comp",115,104,-30,0,12,.665,"dB"},{"Eq",116,106,-30,0,12,.665,"dB"},{"Leveler",117,107,-30,0,12,.665,"dB"},{"Cfc",118,111,-30,0,12,.665,"dB"},{"CfcGain",112,-1,0,20,25,.8,"dB"},{"LevelerGain",108,-1,0,20,25,.8,"dB"},{"AlcGain",109,-1,0,20,25,.8,"dB"},{"AlcGroup",110,-1,-30,0,25,.5,"dB"},{"Agc",5,6,-125,0,125,.5,"dB"},{"AgcGain",4,-1,-50,100,125,.857,"dB"},{"Signal",0,-1,-133,-73,-13,.5,"dBm"},{"SignalAvg",1,-1,-133,-73,-13,.5,"dBm"},{"SignalMaxBin",7,-1,-133,-73,-13,.5,"dBm"},{"Adc",2,3,-120,-20,0,.8333,"dBFS"},{"AdcMax",-1,-1,0,25000,32768,.8333,""},{"PbSnr",8,-1,0,50,60,.8333,"dB"}};
        for(const Row& row:rows) { BarPresetItem face; QVERIFY(face.configureVariant(row.flavor)); QCOMPARE(face.bindingId(),row.primary); QCOMPARE(face.configuration()["secondaryBindingId"].toInt(),row.secondary); QCOMPARE(face.calibratedPosition(row.low),0.0); QVERIFY(qAbs(face.calibratedPosition(row.middle)-row.x)<1e-10); QCOMPARE(face.calibratedPosition(row.high),.99); QCOMPARE(face.configuration()["units"].toString(),QString::fromLatin1(row.units));
            if(row.primary>=0) { face.pushBindingValue(row.primary,-400); face.advanceMeter(0); QVERIFY(!face.hasPrimaryReading()); face.pushBindingValue(row.primary,row.middle); face.advanceMeter(100); QVERIFY(face.hasPrimaryReading()); }
        }
        for(bool mic:{true,false}) { BarPresetItem face; if(mic) { face.configureAsMic(); } else { face.configureAsAlc(); } const int average=mic?103:105,peak=mic?113:114;
            face.pushBindingValue(peak,-400); face.pushBindingValue(average,-400); face.advanceMeter(0); QVERIFY(!face.hasPrimaryReading()); QVERIFY(!face.hasAverageReading());
            face.setBindingUnavailable(peak,"Remote independent peak unavailable"); face.pushBindingValue(average,-12); face.advanceMeter(100); QVERIFY(face.hasAverageReading()); QVERIFY(!face.hasPrimaryReading());
            face.resetForTxTransition(false); face.pushBindingValue(average,-400); face.advanceMeter(200); QVERIFY(!face.hasAverageReading());
        }
        BarPresetItem locked; locked.configureAsMic(); QVERIFY(locked.applyConfiguration({{"minValue",-50},{"maxValue",50}})); QCOMPARE(locked.calibratedPosition(-30),0.0); QCOMPARE(locked.calibratedPosition(0),.665); QCOMPARE(locked.calibratedPosition(12),.99);
        BarPresetItem custom; custom.configureAsCustom(999,-500,10,"Custom"); custom.pushBindingValue(999,-400); custom.advanceMeter(0); QVERIFY(custom.hasPrimaryReading());
    }
    void familySourceTraces() {
        PowerSwrPresetItem power; CrossNeedleItem cross; AnanMultiMeterItem anan; MagicEyePresetItem eye;
        QCOMPARE(power.readingBindings(),(QSet<int>{100,102})); QCOMPARE(cross.readingBindings(),(QSet<int>{100,101})); QCOMPARE(anan.readingBindings(),(QSet<int>{1,200,201,100,102,109,110}));
        for(auto* face:{static_cast<CompositePresetItem*>(&power),static_cast<CompositePresetItem*>(&cross),static_cast<CompositePresetItem*>(&anan),static_cast<CompositePresetItem*>(&eye)}) { QVERIFY(face->applyConfiguration({{"channels",configuredChannels(*face)}})); }
        power.pushBindingValue(100,100); power.pushBindingValue(102,3); power.advanceMeter(0); QCOMPARE(power.channelValue(0),80.0); QCOMPARE(power.channelValue(1),2.6);
        power.pushBindingValue(100,0); power.advanceMeter(100); QCOMPARE(power.channelValue(0),72.0); QCOMPARE(power.channelPeak(0),80.0);
        cross.pushBindingValue(100,100); cross.pushBindingValue(101,10); cross.advanceMeter(0); QCOMPARE(cross.channelValue(0),20.0); QCOMPARE(cross.channelValue(1),2.0);
        cross.pushBindingValue(100,0); cross.advanceMeter(100); QCOMPARE(cross.channelValue(0),18.0); QCOMPARE(cross.channelPeak(0),20.0);
        eye.pushBindingValue(1,-73); eye.advanceMeter(0); QVERIFY(qAbs(eye.channelValue(0)+116.2)<1e-10); eye.pushBindingValue(1,-127); eye.advanceMeter(100); QVERIFY(qAbs(eye.channelValue(0)+116.74)<1e-10);
        anan.pushBindingValue(1,-73); anan.pushBindingValue(200,15); anan.pushBindingValue(201,10); anan.pushBindingValue(100,100); anan.pushBindingValue(110,0); anan.advanceMeter(0);
        QCOMPARE(anan.channelValue(0),-83.8); QCOMPARE(anan.channelValue(1),11.0); QCOMPARE(anan.channelValue(2),2.0); QCOMPARE(anan.channelValue(3),20.0); QCOMPARE(anan.channelValue(6),-24.0);
        QVERIFY(anan.channelVisible(0)); QVERIFY(!anan.channelVisible(3)); anan.resetForTxTransition(true); QVERIFY(!anan.channelVisible(0)); QVERIFY(anan.channelVisible(3)); QVERIFY(!anan.channelHasReading(3));
        QVERIFY(anan.applyConfiguration({{"displayGroup",3}})); QVERIFY(anan.channelVisible(6)); QVERIFY(!anan.channelVisible(3)); QCOMPARE(anan.calibratedPoint(1,12.5),QPointF(.605,.772)); QCOMPARE(anan.calibratedPoint(6,-30),QPointF(.295,.804));
        for(int rating:{1,5,10,30,100,200,500}) { power.setPowerScale(rating); QCOMPARE(power.calibratedPoint(0,rating),QPointF(.75,0)); cross.setPowerScale(rating); QCOMPARE(cross.calibratedPoint(0,rating),QPointF(.662,.083)); }
        power.setPowerScale(5); QCOMPARE(power.calibratedPoint(0,.25),QPointF(.1875,0));
        cross.setPowerScale(100); const QRectF r(0,0,400,312.8); const QPointF pivot=cross.needlePivot(0,r); QCOMPARE(pivot,QPointF(328.8,347.5208));
        // Source angular algorithm with width-derived radii: independent oracle at 0W.
        const double angle=std::atan2(347.5208-.732*312.8,328.8-.052*400)+M_PI;
        const QPointF expected=pivot+QPointF(std::cos(angle)*324,std::sin(angle)*324); QVERIFY(QLineF(expected,cross.needleTip(0,0,r)).length()<1e-9);
        cross.setBindingUnavailable(101,"No reflected sample"); QVERIFY(!cross.channelHasReading(1)); QVERIFY(cross.channelHasReading(0));
    }
    void signalFrequencyAndConcreteControls() {
        SignalTextPresetItem signal; signal.setUnitMode(MeterItem::MeterUnit::S); QCOMPARE(signal.signalReadout(-73),QStringLiteral("S9")); signal.setAboveS9Frequency(true); QCOMPARE(signal.signalReadout(-93),QStringLiteral("S9")); QCOMPARE(signal.signalReadout(-66),QStringLiteral("S9+20"));
        ContestPresetItem contest; QCOMPARE(contest.internalItems().size(),4); QVERIFY(contest.vfoDisplay()->unavailableText().contains("No live")); contest.setFrequency(14200123); QCOMPARE(contest.vfoDisplay()->frequency(),qint64(14200123)); contest.setUnavailableText({});
        RadioModel model; model.addSlice(); model.addSlice(); model.setActiveSliceById(1);
        auto* a=model.sliceById(0); auto* b=model.sliceById(1); a->setFrequency(14100000); b->setFrequency(3700000);
        ContainerButtonDispatcher::Hooks hooks; bool held=false; hooks.sliceRefusal=[&](int) { return held?QStringLiteral("This slice is held by another device"):QString(); };
        ContainerButtonDispatcher dispatcher(&model,std::move(hooks)); dispatcher.applySliceAvailability(contest.bandButtons(),1); dispatcher.applySliceAvailability(contest.modeButtons(),1);
        QObject::connect(contest.bandButtons(),&BandButtonItem::bandClicked,&contest,[&](int band) { dispatcher.clickBand(band,1); });
        QObject::connect(contest.modeButtons(),&ModeButtonItem::modeClicked,&contest,[&](int mode) { if(dispatcher.sliceFor(1)) { a->setDspMode(SliceModel::modeFromName(ModeButtonItem::modeLabel(mode))); } });
        QSignalSpy bands(contest.bandButtons(),&BandButtonItem::bandClicked),modes(contest.modeButtons(),&ModeButtonItem::modeClicked);
        QMouseEvent press(QEvent::MouseButtonPress,QPointF(35,98),Qt::LeftButton,Qt::LeftButton,Qt::NoModifier),release(QEvent::MouseButtonRelease,QPointF(35,98),Qt::LeftButton,Qt::NoButton,Qt::NoModifier);
        QVERIFY(contest.handleMousePress(&press,360,280)); QVERIFY(contest.handleMouseRelease(&release,360,280)); QCOMPARE(bands.count(),1); QCOMPARE(bandFromFrequency(a->frequency()),Band::Band160m); QCOMPARE(b->frequency(),3700000.0);
        held=true; dispatcher.applySliceAvailability(contest.bandButtons(),1); contest.handleMousePress(&press,360,280); contest.handleMouseRelease(&release,360,280); QCOMPARE(bands.count(),1); held=false; dispatcher.applySliceAvailability(contest.bandButtons(),1);
        QMouseEvent mp(QEvent::MouseButtonPress,QPointF(35,195),Qt::LeftButton,Qt::LeftButton,Qt::NoModifier),mr(QEvent::MouseButtonRelease,QPointF(35,195),Qt::LeftButton,Qt::NoButton,Qt::NoModifier);
        QVERIFY(contest.handleMousePress(&mp,360,280)); QVERIFY(contest.handleMouseRelease(&mr,360,280)); QCOMPARE(modes.count(),1); QCOMPARE(a->dspMode(),DSPMode::LSB);
        contest.setPreviewInert(true); QVERIFY(!contest.handleMousePress(&press,360,280)); contest.bandButtons()->handleMousePress(&press,360,280); contest.bandButtons()->handleMouseRelease(&release,360,280); QCOMPARE(bands.count(),1); QVERIFY(contest.bandButtons()->signalsBlocked());
    }
    void pollerReplayAbsenceAndMmio() {
        RadioModel model(RadioModel::Role::Remote); model.setStationConnectionState(ConnectionState::Connected);
        MeterPoller poller; poller.setPaReadingsModel(&model); poller.setRadioStatus(&model.radioStatus());
        MeterWidget live, replacement; auto* power=new PowerSwrPresetItem(&live); live.addItem(power); poller.addTarget(&live);
        poller.setInTx(true); model.radioStatus().setPowerReadings(50,2,1.5); QVERIFY(QMetaObject::invokeMethod(&poller,"poll",Qt::DirectConnection)); live.advanceMeters(0); QVERIFY(power->channelHasReading(0));
        poller.setInTx(false); poller.removeTarget(&live);
        auto* fresh=new PowerSwrPresetItem(&replacement); replacement.addItem(fresh); auto* mic=new BarPresetItem(&replacement); mic->configureAsMic(); replacement.addItem(mic); poller.addTarget(&replacement); replacement.advanceMeters(100);
        QVERIFY(!fresh->channelHasReading(0)); QVERIFY(!fresh->channelHasReading(1)); QVERIFY(!mic->hasPrimaryReading()); QVERIFY(!mic->hasAverageReading());
        model.setStationConnectionState(ConnectionState::Disconnected); poller.replayReadings(&replacement,{}); replacement.advanceMeters(200); QVERIFY(!fresh->channelHasReading(0));
        BarPresetItem custom; custom.configureAsCustom(MeterBinding::SignalPeak,-500,100,"MMIO"); custom.setMmioBinding(QUuid::createUuid(),"Reading"); custom.pushBindingValue(MeterBinding::SignalPeak,-400); custom.advanceMeter(0); QVERIFY(custom.hasPrimaryReading()); QVERIFY(!custom.isNoReading(-400)); custom.setBindingUnavailable(MeterBinding::SignalPeak,"Missing numeric MMIO source"); QVERIFY(!custom.hasPrimaryReading());
    }
    void staticChangesAreConsumedOnce() {
        PowerSwrPresetItem power; QVERIFY(power.takeStaticPresentationChange()); QVERIFY(!power.takeStaticPresentationChange()); QVERIFY(power.applyConfiguration({{"backdropColor","#ff102030"}})); QVERIFY(power.takeStaticPresentationChange()); QVERIFY(!power.takeStaticPresentationChange());
        power.pushBindingValue(100,50); power.advanceMeter(0); QVERIFY(!power.takeStaticPresentationChange()); power.setPowerScale(5); QVERIFY(power.takeStaticPresentationChange()); power.setPowerScale(5); QVERIFY(!power.takeStaticPresentationChange());
        AnanMultiMeterItem anan; anan.takeStaticPresentationChange(); anan.setAboveS9Frequency(true); QVERIFY(anan.takeStaticPresentationChange()); anan.setAboveS9Frequency(true); QVERIFY(!anan.takeStaticPresentationChange()); QVERIFY(anan.applyConfiguration({{"displayGroup",2}})); QVERIFY(anan.takeStaticPresentationChange());
        BarPresetItem bar; bar.configureAsMic(); bar.takeStaticPresentationChange(); QVERIFY(bar.applyConfiguration({{"titleColor","#ffff0000"}})); QVERIFY(bar.takeStaticPresentationChange()); QVERIFY(!bar.takeStaticPresentationChange());
        auto channels=power.configuration()["channels"].toArray(); auto first=channels[0].toObject(); first["bindingId"]=MeterBinding::TxReversePower; channels[0]=first; QVERIFY(power.applyConfiguration({{"channels",channels}})); QCOMPARE(power.readingBindings(),(QSet<int>{101,102}));
    }
    void historySamplingOutlivesFasterSharedFrames() {
        CompositePresetItem history(CompositePresetItem::Face::History);
        auto channels=configuredChannels(history); auto c=channels[0].toObject();
        c["attack"]=1; c["decay"]=1; c["updateIntervalMs"]=250; c["color"]="#ff00ff00"; channels[0]=c;
        QVERIFY(history.applyConfiguration({{"channels",channels},{"historyMs",1200},{"historyCapacity",4},{"autoScale",false},{"minValue",-140},{"maxValue",0},{"showReadout",false},{"faceHeight",240}}));
        auto trace=[&](int right=640) {
            QImage image(640,240,QImage::Format_ARGB32_Premultiplied); image.fill(Qt::transparent);
            QPainter painter(&image); history.paintForLayer(painter,640,240,MeterItem::Layer::OverlayDynamic); painter.end();
            int pixels=0; for(int y=0;y<image.height();++y) { for(int x=0;x<right;++x) { const QColor pixel=image.pixelColor(x,y); if(pixel.green()>200 && pixel.red()<30 && pixel.blue()<30) {++pixels;} } }
            return pixels;
        };
        // Independent timeline: 250 ms sampling on 100 ms shared ticks retains
        // readings at 0,300,600,900, rather than restarting the gate every tick.
        for(int now=0;now<=900;now+=100) {
            const double value=now<300?-120:now<600?-60:now<900?-90:-30;
            history.pushBindingValue(MeterBinding::SignalAvg,value); history.advanceMeter(now);
            if(now==200) {QCOMPARE(trace(),0);}
            if(now==300) {QVERIFY2(trace()>100,"History must draw its second sample despite faster shared frames");}
            if(now==600) {QVERIFY(trace()>200);}
            if(now==900) {QVERIFY(trace()>300);}
        }
        history.setBindingUnavailable(MeterBinding::SignalAvg,"No live reading");
        history.advanceMeter(1000); QVERIFY(trace()>300); // Absence adds no invented sample.
        history.advanceMeter(1799); QVERIFY(trace()>100); // Last two real samples remain.
        history.advanceMeter(2100); QCOMPARE(trace(),0); // Exact duration expires the final sample.
        history.setBindingUnavailable(MeterBinding::SignalAvg,{});
        history.pushBindingValue(MeterBinding::SignalAvg,-80); history.advanceMeter(2200);
        history.pushBindingValue(MeterBinding::SignalAvg,-40); history.advanceMeter(2500); QVERIFY(trace()>100);
        history.resetForTxTransition(true); QCOMPARE(trace(),0); QVERIFY(!history.channelHasReading(0));
        history.pushBindingValue(MeterBinding::SignalAvg,-100); history.advanceMeter(2600);
        history.pushBindingValue(MeterBinding::SignalAvg,-40); history.advanceMeter(2900); QVERIFY(trace()>100);
        history.advanceMeter(50); QCOMPARE(trace(),0); // Rollback drops future trace points.
        history.advanceMeter(350); QVERIFY(trace()>100);
        // A source/configuration reset also starts a new history timeline.
        QVERIFY(history.applyConfiguration({{"historyCapacity",2}})); QCOMPARE(trace(),0);
        for(int now=3000;now<=3900;now+=300) {history.pushBindingValue(MeterBinding::SignalAvg,now==3900?-30:-100);history.advanceMeter(now);}
        QVERIFY(trace()>100); QCOMPARE(trace(475),0); // Capacity retains only 3600→3900, at the right edge.
    }
    void primitiveClockSharesCadence() {
        ContainerContentRegistry registry; MeterWidget widget; widget.resize(360,120); auto* item=registry.createMeterItem(registry.makeEntry("CLOCK"),&widget); QVERIFY(item); widget.addItem(item); widget.show();
#ifdef NEREUS_GPU_SPECTRUM
        QSignalSpy submitted(&widget,&QRhiWidget::frameSubmitted); widget.advanceMeters(0); const int before=submitted.count(); widget.update(); QTRY_VERIFY_WITH_TIMEOUT(submitted.count()>before,2000); const QImage first=widget.grabFramebuffer();
#else
        widget.advanceMeters(0); QTest::qWait(50); const QImage first=widget.grab().toImage();
#endif
        QVERIFY(!item->advanceMeter(100)); QTest::qWait(1100); widget.advanceMeters(1100);
#ifdef NEREUS_GPU_SPECTRUM
        const int next=submitted.count(); widget.update(); QTRY_VERIFY_WITH_TIMEOUT(submitted.count()>next,2000); const QImage last=widget.grabFramebuffer();
#else
        widget.update(); QTest::qWait(30); const QImage last=widget.grab().toImage();
#endif
        QVERIFY(!first.isNull()); QVERIFY(first!=last);
    }
    void nativeFamilyFrames() {
        const QString destination=qEnvironmentVariable("NEREUS_METER_CAPTURE_DIR"); ContainerContentRegistry registry;
        for(const QString& type:{"meter.powerSwr","meter.crossNeedle","meter.ananMulti","meter.magicEye","meter.signalText","meter.historyGraph","meter.vfoDisplay","meter.clock","meter.contest","meter.eq"}) {
            for(int width:{360,640}) {
                MeterWidget widget; ContentEntry entry=registry.makeEntry(type); auto* item=registry.createMeterItem(entry,&widget); QVERIFY(item);
                auto* face=qobject_cast<CompositePresetItem*>(item); if(face) { QVERIFY(face->applyConfiguration({{"channels",configuredChannels(*face)}})); if(type=="meter.ananMulti") { face->resetForTxTransition(true); } face->setFrequency(14200123); face->setModeLabel("USB"); face->setBandLabel("20m"); }
                widget.resize(width,face?face->preferredFaceHeight():72); widget.addItem(item); if(type=="meter.ananMulti") { widget.resetForTxTransition(true); } widget.show(); QTest::qWait(100);
#ifdef NEREUS_GPU_SPECTRUM
                QSignalSpy submitted(&widget,&QRhiWidget::frameSubmitted);
#endif
                QImage first,last;
                for(int frame=0;frame<12;++frame) {
                    for(int binding:item->readingBindings()) { const double value=binding==1 ? -110+frame*4 : binding==200 ? 13.8 : binding==201 ? 6 : binding==102 ? 1+frame*.15 : binding>=100 && binding<=101 ? frame*9 : binding==110 ? -30+frame*3 : -25+frame*3; widget.updateMeterValue(binding,value); }
                    widget.advanceMeters(frame*100);
#ifdef NEREUS_GPU_SPECTRUM
                    const int before=submitted.count(); widget.update(); QTRY_VERIFY_WITH_TIMEOUT(submitted.count()>before,2000); const QImage image=widget.grabFramebuffer();
#else
                    widget.update(); QTest::qWait(10); const QImage image=widget.grab().toImage();
#endif
                    QVERIFY(!image.isNull());
                    if(type=="meter.ananMulti" && frame==11) {
                        // A native DPR reference catches logical-resolution background upscaling.
                        QImage reference(image.size(),QImage::Format_RGBA8888); reference.setDevicePixelRatio(widget.devicePixelRatioF()); reference.fill(QColor(15,15,26));
                        { QPainter painter(&reference); face->paintForLayer(painter,width,widget.height(),MeterItem::Layer::Background); }
                        int mismatches=0,total=0; const double dpr=widget.devicePixelRatioF();
                        for(int y=0;y<qRound(22*dpr);++y) { for(int x=qRound(35*dpr);x<qRound((width-110)*dpr);++x) { const QColor actual=image.pixelColor(x,y),expected=reference.pixelColor(x,y); ++total; if(qAbs(actual.red()-expected.red())>2 || qAbs(actual.green()-expected.green())>2 || qAbs(actual.blue()-expected.blue())>2) { ++mismatches; } } }
                        QVERIFY2(mismatches<total/100,qPrintable(QString("Static title DPR mismatches %1/%2").arg(mismatches).arg(total)));
                    }
                    if(type=="meter.powerSwr" && frame==11) {
                        const double scale=double(image.width())/width;
                        // Independent .8 recurrence: inputs 0,9,...99 => 96.75000009216W.
                        const double position=.5625+(96.75000009216-50)/50*.1875;
                        const QColor marker=image.pixelColor(qRound((18+(width-36)*position)*scale),qRound(48*scale)); QVERIFY(marker.red()>200 && marker.green()>200 && marker.blue()<50);
                        const QColor band=image.pixelColor(qRound((18+(width-36)*.45)*scale),qRound(29*scale)); QVERIFY(qAbs(band.red()-144)<=3 && qAbs(band.green()-16)<=3 && qAbs(band.blue()-16)<=3);
                    }
                    if(frame==0) { first=image; } last=image;
                    if(!destination.isEmpty() && (frame==0 || frame==11)) { QDir().mkpath(destination); QVERIFY(image.save(destination+"/"+type.mid(6)+"-"+QString::number(width)+"-"+QString::number(frame)+".png")); }
                }
                if(!item->readingBindings().isEmpty()) { QVERIFY(first!=last); }
                if(face && face->vfoDisplay()) {
                    face->setFrequency(7150123); widget.advanceMeters(1300);
#ifdef NEREUS_GPU_SPECTRUM
                    const int before=submitted.count(); widget.update(); QTRY_VERIFY_WITH_TIMEOUT(submitted.count()>before,2000); const QImage changed=widget.grabFramebuffer();
#else
                    widget.update(); QTest::qWait(15); const QImage changed=widget.grab().toImage();
#endif
                    QVERIFY(changed!=last);
                }
                if(face) { QJsonObject changes; if(face->editableFields().contains("backdropColor")) { changes["backdropColor"]="#ff102030"; } if(face->editableFields().contains("titleColor")) { changes["titleColor"]="#ffff0000"; } QVERIFY(face->applyConfiguration(changes)); widget.advanceMeters(1500);
#ifdef NEREUS_GPU_SPECTRUM
                    const int before=submitted.count(); widget.update(); QTRY_VERIFY_WITH_TIMEOUT(submitted.count()>before,2000); const QImage customized=widget.grabFramebuffer();
#else
                    widget.update(); QTest::qWait(15); const QImage customized=widget.grab().toImage();
#endif
                    if(changes.contains("backdropColor")) { QCOMPARE(customized.pixelColor(1,customized.height()-2),QColor(16,32,48)); QVERIFY(customized!=last); }
                    if(!destination.isEmpty()) { QVERIFY(customized.save(destination+"/"+type.mid(6)+"-"+QString::number(width)+"-customized.png")); }
                }
                const int staticChecks=type=="meter.ananMulti" ? 2 : (type=="meter.powerSwr" || type=="meter.eq" ? 1 : 0);
                for(int check=0;check<staticChecks;++check) {
                    if(type=="meter.ananMulti" && check==1) {
                        widget.resetForTxTransition(false); widget.advanceMeters(1650);
#ifdef NEREUS_GPU_SPECTRUM
                        const int before=submitted.count(); widget.update(); QTRY_VERIFY_WITH_TIMEOUT(submitted.count()>before,2000);
#else
                        widget.update(); QTest::qWait(15);
#endif
                    }
#ifdef NEREUS_GPU_SPECTRUM
                    const QImage previous=widget.grabFramebuffer();
#else
                    const QImage previous=widget.grab().toImage();
#endif
                    if(type=="meter.powerSwr") { face->setPowerScale(5); }
                    else if(type=="meter.ananMulti" && check==0) { QVERIFY(face->applyConfiguration({{"displayGroup",2}})); }
                    else if(type=="meter.ananMulti") { face->setAboveS9Frequency(true); }
                    else { QVERIFY(qobject_cast<BarPresetItem*>(item)->applyConfiguration({{"titleColor","#ffff0000"}})); }
                    widget.advanceMeters(1600+check*100);
#ifdef NEREUS_GPU_SPECTRUM
                    const int before=submitted.count(); widget.update(); QTRY_VERIFY_WITH_TIMEOUT(submitted.count()>before,2000); const QImage changed=widget.grabFramebuffer();
#else
                    widget.update(); QTest::qWait(15); const QImage changed=widget.grab().toImage();
#endif
                    QVERIFY2(changed!=previous,qPrintable(type+" static check "+QString::number(check))); QVERIFY(!item->takeStaticPresentationChange());
                }
                qInfo()<<"Native"<<QGuiApplication::platformName()<<type<<width<<"DPR"<<widget.devicePixelRatioF();
#ifdef NEREUS_GPU_SPECTRUM
                qInfo()<<"QRhi API"<<int(widget.api())<<"frames"<<submitted.count();
#endif
            }
        }
    }
};
QTEST_MAIN(TestCompositePresets)
#include "tst_meter_composite_presets.moc"
