#!/usr/bin/env python3
# Run manually: python3 scripts/gen-tci-matrix-readme.py > docs/architecture/phase3j-tci-matrix/README.md
#
# Reads tests/data/tci/matrix.csv and emits a markdown table suitable for
# dropping into the TCI port design doc as a verification reference.
# Run this at the end of each phase (Phase 25/27) to regenerate the README.
#
# Grouping: rows are grouped by command family, inferred from the command
# column prefix up to the first colon (e.g. "vfo:0:0:14200000;" -> "vfo").
# Rows whose command has no colon are grouped under "other".

import sys
from datetime import datetime, timezone
from pathlib import Path

MATRIX_PATH = Path(__file__).parent.parent / "tests" / "data" / "tci" / "matrix.csv"

HEADER = """\
<!-- AUTO-GENERATED by scripts/gen-tci-matrix-readme.py — do not edit by hand -->
<!-- Generated at: {timestamp} -->
<!-- Source: tests/data/tci/matrix.csv -->

# TCI Verification Matrix

This table is auto-generated from `tests/data/tci/matrix.csv`.
Each row corresponds to a single Thetis behavior exercised by the
`tst_tci_matrix_runner` test.

"""

TABLE_HEADER = """\
| Command | Input | Expected Response | Expected Notifications | Thetis Cite | Notes |
|---------|-------|-------------------|------------------------|-------------|-------|
"""


def smart_split(line: str, delimiter: str = ',') -> list[str]:
    """Split a CSV line on delimiter, respecting backslash escapes (\\, -> ,).

    The matrix.csv uses \\, to embed commas in TCI command fields such as
    vfo:0\\,0\\,14250000; so that the CSV parser does not treat them as column
    separators.  Python's csv module has no escape-char=\\\\ mode that also
    suppresses quoting, so we implement the split manually.

    This mirrors the C++ smartSplit logic used by tst_tci_matrix_runner.cpp
    to parse the same CSV at test time.
    """
    parts: list[str] = []
    current: list[str] = []
    prev_backslash = False
    for ch in line:
        if prev_backslash:
            current.append(ch)
            prev_backslash = False
        elif ch == '\\':
            prev_backslash = True
        elif ch == delimiter:
            parts.append(''.join(current))
            current = []
        else:
            current.append(ch)
    if prev_backslash:
        current.append('\\')  # trailing lone backslash
    parts.append(''.join(current))
    return parts


COLUMN_NAMES = [
    "command", "input", "expected_response",
    "expected_notifications", "thetis_cite", "notes",
]


def parse_matrix_csv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    """Parse matrix.csv using smart_split, return (header, rows)."""
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines:
        return [], []
    header = smart_split(lines[0])
    rows: list[dict[str, str]] = []
    for raw in lines[1:]:
        raw = raw.rstrip('\r\n')
        if not raw:
            continue
        values = smart_split(raw)
        # Pad short rows; truncate long rows to header width.
        while len(values) < len(header):
            values.append("")
        row = dict(zip(header, values[:len(header)]))
        rows.append(row)
    return header, rows


def command_family(command: str) -> str:
    """Infer the command family from the command column."""
    colon = command.find(":")
    if colon == -1:
        return "other"
    return command[:colon].strip().lower() or "other"


def escape_cell(text: str) -> str:
    """Escape pipe characters so the markdown table cell stays intact."""
    return text.replace("|", "&#124;")


def main() -> None:
    if not MATRIX_PATH.exists():
        print(f"ERROR: matrix CSV not found at {MATRIX_PATH}", file=sys.stderr)
        sys.exit(1)

    _header, rows = parse_matrix_csv(MATRIX_PATH)

    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    print(HEADER.format(timestamp=timestamp), end="")

    # Group rows by command family.
    groups: dict[str, list[dict]] = {}
    for row in rows:
        family = command_family(row.get("command", ""))
        groups.setdefault(family, []).append(row)

    if not groups:
        print("*No data rows yet — rows are added per phase (Phase 5 onward).*\n")
        return

    for family, family_rows in sorted(groups.items()):
        print(f"## `{family}` commands\n")
        print(TABLE_HEADER, end="")
        for row in family_rows:
            cols = [
                escape_cell(row.get("command", "")),
                escape_cell(row.get("input", "")),
                escape_cell(row.get("expected_response", "")),
                escape_cell(row.get("expected_notifications", "")),
                escape_cell(row.get("thetis_cite", "")),
                escape_cell(row.get("notes", "")),
            ]
            print("| " + " | ".join(cols) + " |")
        print()


if __name__ == "__main__":
    main()
