// NereusSDR for iOS: test-only WSS relay socket anchored to one ephemeral CA
// SPDX-License-Identifier: GPL-3.0-or-later WITH AdditionRef-NereusSDR-AppStore-permission

#if os(macOS)

import Foundation
import NereusLink
import Security

/// URLSession's WebSocket implementation with trust restricted to the CA
/// generated by LocalRendezvous.WebRelay for this one test run. The normal
/// production socket and the machine's trusted roots are untouched.
final class ScopedRelaySocket: NSObject, RelayBinarySocket, URLSessionDelegate, @unchecked Sendable {
    private let anchor: SecCertificate
    private var session: URLSession!
    private var task: URLSessionWebSocketTask!

    private init(anchor: SecCertificate) {
        self.anchor = anchor
        super.init()
    }

    static func connect(to url: URL, authority: URL) async throws -> any RelayBinarySocket {
        let pem = try String(contentsOf: authority, encoding: .utf8)
        let base64 = pem.split(whereSeparator: \.isNewline)
            .filter { !$0.hasPrefix("-----") }.joined()
        guard let der = Data(base64Encoded: base64),
              let anchor = SecCertificateCreateWithData(nil, der as CFData) else {
            throw LocalRendezvous.Failure(description: "the scoped relay CA is invalid")
        }
        let socket = ScopedRelaySocket(anchor: anchor)
        socket.session = URLSession(configuration: .ephemeral, delegate: socket, delegateQueue: nil)
        socket.task = socket.session.webSocketTask(with: url)
        socket.task.resume()
        return socket
    }

    func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge,
                    completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        guard challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust,
              let trust = challenge.protectionSpace.serverTrust,
              SecTrustSetPolicies(trust, SecPolicyCreateSSL(true, "127.0.0.1" as CFString)) == errSecSuccess,
              SecTrustSetAnchorCertificates(trust, [anchor] as CFArray) == errSecSuccess,
              SecTrustSetAnchorCertificatesOnly(trust, true) == errSecSuccess,
              SecTrustEvaluateWithError(trust, nil) else {
            completionHandler(.cancelAuthenticationChallenge, nil)
            return
        }
        completionHandler(.useCredential, URLCredential(trust: trust))
    }

    func nextEvent() async -> RelaySocketEvent? {
        do {
            switch try await task.receive() {
            case .data(let data): return .binary(data)
            case .string: return .text
            @unknown default: return .closed
            }
        } catch {
            return .closed
        }
    }

    func send(_ message: Data) async throws {
        try await task.send(.data(message))
    }

    func close() async {
        task.cancel(with: .normalClosure, reason: nil)
        session.invalidateAndCancel()
    }
}

#endif
